// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://slaymjmqnfwspwzvoikk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNsYXltam1xbmZ3c3B3enZvaWtrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxMTQ2MjUsImV4cCI6MjA2OTY5MDYyNX0.l6mIGPnzEqBgirN2dj34TQt545Aawg5E_R8IVOjwLQI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});